name: Publish
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  buildNode:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch:
          - amd64
          - arm64
          - ppc64el
          # - armhf
          # - armel
          # - s390x
        version:
          - "18.x"
          #- "17.x"
          - "16.x"
          #- "15.x"
    name: "Build, Node: ${{ matrix.version }}, Arch: ${{ matrix.arch }}"
    steps:
      # Get code
      - name: Checkout
        uses: actions/checkout@v2

      # Setup node
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: current

      # Install dependencies
      - run: npm ci

      # Build bin
      - name: Build packages
        run: npm run start -- build --arch "${{ matrix.arch }}" --version "${{ matrix.version }}"

      - name: Upload debian package file
        uses: actions/upload-artifact@v3
        with:
          name: "nodejs_${{ matrix.arch }}_${{ matrix.version }}"
          path: "*.deb"
