name: Publish
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - name: Build packages
        env:
          MAXREQ: "40"
        run: npm run start -- -n all -a all --ci "${{ secrets.GITHUB_TOKEN }}"
