name: Publish
on:
  workflow_dispatch:
    inputs:
      node_version:
        description: "Node.js version to use for the release"
        required: true
        default: latest
        type: string
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: |
          if [[ "${{ github.event.inputs.node_version }}" == "latest" ]]; then
            npm run start -- -n latest -a all
          else
            npm run start -- -n all -a all
          fi
      - uses: softprops/action-gh-release@v1
        with:
          name: Node pre build binaries
          tag_name: "node_${{ github.run_id }}"
          body: "Node pre build binaries"
          files: "*.deb"
